import {test,expect} from '@playwright/test';
import {clock,advance,move,routeAction} from './helpers.ts';
import {MISSIONS} from '../../src/campaign-content.ts';
import {contractById} from '../../src/contract-content.ts';
import {Game} from '../../src/engine.ts';
import {Campaign} from '../../src/campaign.ts';

test.beforeEach(async({page})=>{
  await clock(page);
  await page.addInitScript(()=>localStorage.setItem('echo-heist-scene-detail','false'));
});
test('contract saves cannot bypass main completion, and the locked board pauses gameplay',async({page})=>{
  await page.addInitScript(()=>localStorage.setItem('echo-heist-contracts-v1',JSON.stringify({version:1,rotation:1,active:'station-window',inContracts:true,scores:{}})));
  await page.goto('/'); await advance(page); await page.locator('#story-skip').click();
  await page.locator('#overlay-action').click(); await advance(page,15);
  const before=await page.locator('#seconds').textContent();
  await page.locator('#contracts-button').click(); await move(page,'d',60);
  await expect(page.locator('#seconds')).toHaveText(before!);
  await expect(page.locator('#contracts-intro')).toContainText('完成八章主线后');
  await expect(page.locator('[data-contract]')).toHaveCount(0);
  await expect(page.locator('#contracts-refresh')).toBeDisabled();
  await page.locator('#contracts-close').click(); await advance(page);
  await expect(page.locator('#mission-title')).toHaveText('一道需要两个人的门');
  await expect(page.locator('#record-label')).toHaveText('PAUSED');
});

test('a real contract records one echo, freezes through reload, settles once and leaves the main story untouched',async({page})=>{
  if(process.env.CI || process.env.ECHO_SOFTWARE_WEBGL)test.setTimeout(300_000);
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  const ids=MISSIONS.filter(m=>m.chapter!=='机制试验').map(m=>m.id);
  await page.addInitScript(ids=>{
    if(!localStorage.getItem('echo-heist-campaign-v1'))localStorage.setItem('echo-heist-campaign-v1',JSON.stringify({version:1,selected:'C0-1',runs:Object.fromEntries(ids.map(id=>[id,[]])),completed:ids}));
    if(!localStorage.getItem('echo-heist-story-v1'))localStorage.setItem('echo-heist-story-v1',JSON.stringify({version:1,seen:['c0-arrival'],choices:{}}));
  },ids);
  await page.goto('/');await advance(page);
  const main=await page.evaluate(()=>[localStorage.getItem('echo-heist-campaign-v1'),localStorage.getItem('echo-heist-plans-v1'),localStorage.getItem('echo-heist-story-v1'),localStorage.getItem('echo-heist-progress-v1')]);
  await page.locator('#contracts-button').click();
  await expect(page.locator('#contract-offers [data-contract]')).toHaveCount(3);
  await page.screenshot({path:'.local/contracts-desktop.png'});
  await page.locator('[data-contract="station-platform"]').click();await advance(page);
  await expect(page.locator('#echo-count')).toHaveText('0 / 1');
  await expect(page.locator('#contract-conditions')).toContainText('最多 1 名回声');
  await expect(page.locator('.overlay-copy')).toHaveText(contractById('station-platform')!.request);
  await expect(page.locator('#mission-board')).not.toBeVisible();
  const c=contractById('station-platform')!, split=c.stage.witness.findIndex(a=>'record' in a);
  let model=new Game(c.stage.level);
  for(const action of c.stage.witness.slice(0,split+1))await routeAction(page,model,action);
  await advance(page,3);
  await expect(page.locator('#echo-count')).toHaveText('1 / 1');
  await page.keyboard.press('r');await advance(page);
  await expect(page.locator('#echo-count')).toHaveText('1 / 1');
  const checkpoint=await page.evaluate(()=>localStorage.getItem('echo-heist-contracts-v1'));
  await page.locator('#preview-button').click();
  await page.locator('#preview-frame').fill('720');await page.locator('#preview-frame').dispatchEvent('input');await advance(page);
  await page.locator('#contracts-button').click();
  await expect(page.locator('#contracts-refresh')).toBeDisabled();
  await expect(page.locator('[data-contract="station-platform"]')).toBeDisabled();
  await page.locator('#contracts-close').click();
  expect(await page.evaluate(()=>localStorage.getItem('echo-heist-contracts-v1'))).toBe(checkpoint);
  await page.reload();await advance(page);
  await expect(page.locator('#mission-title')).toHaveText(c.title);
  await expect(page.locator('#echo-count')).toHaveText('1 / 1');
  await expect(page.locator('#seconds')).toHaveText('12');
  await page.locator('#overlay-action').click();await advance(page,15);
  await page.locator('#retry-button').click();await advance(page);
  await expect(page.locator('#credential-owner')).toContainText('S');
  await page.reload();await advance(page);
  const plan=await page.evaluate(()=>JSON.parse(localStorage.getItem('echo-heist-contract-plans-v1')!)['CT-station-platform']);
  model=new Game(c.stage.level);model.restorePlan(plan.echoes);
  for(const action of c.stage.witness.slice(split+1))await routeAction(page,model,action);
  await expect(page.locator('#overlay-card h2')).toContainText('已交差');
  const settled=await page.evaluate(()=>JSON.parse(localStorage.getItem('echo-heist-contracts-v1')!));
  expect(settled.scores[c.id].completions).toBe(1);expect(settled.scores[c.id].fewestEchoes).toBe(1);
  await advance(page,60);
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('echo-heist-contracts-v1')!).scores['station-platform'].completions)).toBe(1);
  await page.locator('#overlay-action').click();
  await expect(page.locator('#contracts-records')).toContainText('最快成功回合');
  await page.locator('#contracts-refresh').click();
  await expect(page.locator('[data-contract="station-window"]')).toBeVisible();
  await expect(page.locator('#contracts-active')).toContainText('送件的人');
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.local/contracts-phone.png',fullPage:true});
  expect(await page.locator('#contracts-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);
  await page.locator('[data-contract="station-window"]').click();await advance(page);
  await expect(page.locator('#echo-count')).toHaveText('0 / 2');
  await page.reload();await advance(page);await expect(page.locator('#mission-title')).toHaveText('南窗只开三秒');
  await page.locator('#contracts-button').click();await page.locator('#contracts-leave').click();await advance(page);
  await expect(page.locator('#mission-title')).toHaveText('一道需要两个人的门');
  expect(await page.evaluate(()=>[localStorage.getItem('echo-heist-campaign-v1'),localStorage.getItem('echo-heist-plans-v1'),localStorage.getItem('echo-heist-story-v1'),localStorage.getItem('echo-heist-progress-v1')])).toEqual(main);
  expect(errors).toEqual([]);
});

test('an active contract cannot override explicit demo or training navigation',async({page})=>{
  const ids=MISSIONS.filter(m=>m.chapter!=='机制试验').map(m=>m.id);
  const save=new Campaign({version:1,selected:'C0-1',runs:Object.fromEntries(ids.map(id=>[id,[]])),completed:ids}).export();
  await page.addInitScript(save=>{
    if(!localStorage.getItem('echo-heist-campaign-v1'))localStorage.setItem('echo-heist-campaign-v1',JSON.stringify(save));
    if(!localStorage.getItem('echo-heist-contracts-v1'))localStorage.setItem('echo-heist-contracts-v1',JSON.stringify({version:1,rotation:0,active:'station-platform',inContracts:true,scores:{}}));
  },save);
  await page.goto('/?demo=station-transfer');await advance(page);
  await expect(page.locator('#chapter-label')).toContainText('独立试玩');
  await expect(page.locator('#contracts-button')).not.toBeVisible();
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('echo-heist-campaign-v1')!))).toEqual(save);
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('echo-heist-contracts-v1')!).inContracts)).toBe(true);
  await page.goto('/');await advance(page);
  await expect(page.locator('#mission-title')).toHaveText('送件的人，留下开门');
  await page.goto('/?mode=training');await advance(page);
  await expect(page.locator('#mission-title')).toHaveText('不在场证明');
  await expect(page.locator('#contract-strip')).not.toBeVisible();
  const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('echo-heist-contracts-v1')!));
  expect(state.inContracts).toBe(false);expect(state.active).toBe('station-platform');
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('echo-heist-campaign-v1')!))).toEqual(save);
});
